/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 maya.glb -T 
Files: maya.glb [8.86MB] > /Users/emmanuelserrano/rho_chapter_website/public/models/maya-transformed.glb [314.02KB] (96%)
*/

import React, { useEffect } from 'react';
import { useGLTF } from '@react-three/drei';
import { Color } from 'three';
import useMacbookStore from '../../store';
import { noChangeParts } from '../../constants/index.js';

export default function MayaModel(props) {
  const { color } = useMacbookStore();
  const { nodes, materials, scene } = useGLTF('/models/maya-transformed.glb');

  useEffect(() => {
    scene.traverse((child) => {
      if (child.isMesh) {
        if (!noChangeParts.includes(child.name)) {
          child.material.color = new Color(color);
        }
      }
    });
  }, [color, scene]);

  return (
    <group {...props} dispose={null} scale={[4, 4, 4]}>
      <mesh 
        geometry={nodes.mesh_0.geometry} 
        material={nodes.mesh_0.material}
        rotation={[0, 4, 0]}
      />
    </group>
  );
}

useGLTF.preload('/models/maya-transformed.glb');